apiVersion: skaffold/v2beta7
kind: Config
metadata:
  name: assessment-system-backend
build:
  artifacts:
    - image: us.gcr.io/classroomict/assignment-service
      jib:
        project: assignment-service
#  - image: us.gcr.io/classroomict/assignment-service
#    context: assignment-service
deploy:
  kubectl:
    manifests:
    - ingress.yml
    - assignment-service/k8s-assignment-service.yml
profiles:
  - name: gcp
    activation:
      - kubeContext: my-cluster
    build:
      googleCloudBuild:
        projectId: classroomict
