
spring:
  data:
    mongodb:
      uri: mongodb://root:eQWRv7lGgR@mongodb.default.svc.cluster.local:27017/grading-service-db?authSource=admin
      database: grading-service-db
server:
  port: 8080
  
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://securetoken.google.com/assessment-system-auth
          jwk-set-uri: https://www.googleapis.com/robot/v1/metadata/jwk/securetoken@system.gserviceaccount.com

logging:
  level:
    org.springframework.security: debug

