
server:
  port: 8080
spring:
  data:
    mongodb:
#      authentication-database: admin
      uri: mongodb://root:eQWRv7lGgR@mongodb.default.svc.cluster.local:27017/assignment-service-db?authSource=admin
      auto-index-creation: true
  application:
    name: assignment-service

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://securetoken.google.com/onlinesubmissionsystem
          jwk-set-uri: https://www.googleapis.com/robot/v1/metadata/jwk/securetoken@system.gserviceaccount.com

#      uri: mongodb://localhost:27017/assignment-service-db?authSource=admin